export default function htmlFix(string) {
    return string
        .replace(/(&quot\;)/g,"\"")
        .replace(/(&#039;)/g,"\'")
        .replace(/(&amp;)/g,"\&")
        .replace(/(&agrave;)/g,"\à")
        .replace(/(&Agrave;)/g,"\À")
        .replace(/(&Aacute;)/g,"\Á")
        .replace(/(&Acirc;)/g,"\Â")
        .replace(/(&Atilde;)/g,"\Ã")
        .replace(/(&Aring;)/g,"\Å")
        .replace(/(&aacute;)/g,"\á")
        .replace(/(&acirc;)/g,"\â")
        .replace(/(&atilde;)/g,"\ã")
        .replace(/(&auml;)/g,"\ä")
        .replace(/(&aring;)/g,"\å")
        .replace(/(&AElig;)/g,"\Æ")
        .replace(/(&aelig;)/g,"\æ")
        .replace(/(&szlig;)/g,"\ß")
        .replace(/(&egrave;)/g,"\è")
        .replace(/(&eacute;)/g,"\é")
        .replace(/(&iacute;)/g,"\í")
        .replace(/(&ocirc;)/g,"\ô")
        .replace(/(&ntilde;)/g,"\ñ")
        .replace(/(&deg;)/g,"\°")
        .replace(/(&lt;)/g,"\<")
        .replace(/(&gt;)/g,"\>")
}